jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      name: Build with Maven
      run: mvn install coveralls:report -Dgpg.skip=true -DrepoToken="$COVERALLS_TOKEN"
        -B -V --file pom.xml
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___test.yml
